import 'package:google_mlkit_translation/google_mlkit_translation.dart';

/// Maps ML Kit [TranslateLanguage] to ISO 3166-1 alpha-2 codes for [flutter_countryify] flags.
/// Language→country is approximate (e.g. English → GB, Arabic → SA).
String countryCodeForTranslateLanguage(TranslateLanguage language) {
  switch (language) {
    case TranslateLanguage.afrikaans:
      return 'ZA';
    case TranslateLanguage.albanian:
      return 'AL';
    case TranslateLanguage.arabic:
      return 'SA';
    case TranslateLanguage.belarusian:
      return 'BY';
    case TranslateLanguage.bengali:
      return 'BD';
    case TranslateLanguage.bulgarian:
      return 'BG';
    case TranslateLanguage.catalan:
      return 'ES';
    case TranslateLanguage.chinese:
      return 'CN';
    case TranslateLanguage.croatian:
      return 'HR';
    case TranslateLanguage.czech:
      return 'CZ';
    case TranslateLanguage.danish:
      return 'DK';
    case TranslateLanguage.dutch:
      return 'NL';
    case TranslateLanguage.english:
      return 'GB';
    case TranslateLanguage.esperanto:
      return 'UN';
    case TranslateLanguage.estonian:
      return 'EE';
    case TranslateLanguage.finnish:
      return 'FI';
    case TranslateLanguage.french:
      return 'FR';
    case TranslateLanguage.galician:
      return 'ES';
    case TranslateLanguage.georgian:
      return 'GE';
    case TranslateLanguage.german:
      return 'DE';
    case TranslateLanguage.greek:
      return 'GR';
    case TranslateLanguage.gujarati:
      return 'IN';
    case TranslateLanguage.haitian:
      return 'HT';
    case TranslateLanguage.hebrew:
      return 'IL';
    case TranslateLanguage.hindi:
      return 'IN';
    case TranslateLanguage.hungarian:
      return 'HU';
    case TranslateLanguage.icelandic:
      return 'IS';
    case TranslateLanguage.indonesian:
      return 'ID';
    case TranslateLanguage.irish:
      return 'IE';
    case TranslateLanguage.italian:
      return 'IT';
    case TranslateLanguage.japanese:
      return 'JP';
    case TranslateLanguage.kannada:
      return 'IN';
    case TranslateLanguage.korean:
      return 'KR';
    case TranslateLanguage.latvian:
      return 'LV';
    case TranslateLanguage.lithuanian:
      return 'LT';
    case TranslateLanguage.macedonian:
      return 'MK';
    case TranslateLanguage.malay:
      return 'MY';
    case TranslateLanguage.maltese:
      return 'MT';
    case TranslateLanguage.marathi:
      return 'IN';
    case TranslateLanguage.norwegian:
      return 'NO';
    case TranslateLanguage.persian:
      return 'IR';
    case TranslateLanguage.polish:
      return 'PL';
    case TranslateLanguage.portuguese:
      return 'PT';
    case TranslateLanguage.romanian:
      return 'RO';
    case TranslateLanguage.russian:
      return 'RU';
    case TranslateLanguage.slovak:
      return 'SK';
    case TranslateLanguage.slovenian:
      return 'SI';
    case TranslateLanguage.spanish:
      return 'ES';
    case TranslateLanguage.swahili:
      return 'KE';
    case TranslateLanguage.swedish:
      return 'SE';
    case TranslateLanguage.tagalog:
      return 'PH';
    case TranslateLanguage.tamil:
      return 'IN';
    case TranslateLanguage.telugu:
      return 'IN';
    case TranslateLanguage.thai:
      return 'TH';
    case TranslateLanguage.turkish:
      return 'TR';
    case TranslateLanguage.ukrainian:
      return 'UA';
    case TranslateLanguage.urdu:
      return 'PK';
    case TranslateLanguage.vietnamese:
      return 'VN';
    case TranslateLanguage.welsh:
      return 'GB';
  }
}
