// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmGY7s3NktzsXmNriOZsjAl_0VOpxsf7U',
    appId: '1:386381768273:web:711c651c8540f0bffd7a70',
    messagingSenderId: '386381768273',
    projectId: 'transmirror-8eedf',
    authDomain: 'transmirror-8eedf.firebaseapp.com',
    storageBucket: 'transmirror-8eedf.firebasestorage.app',
    measurementId: 'G-09PZRC2N9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEINbHZqo7iTmoXd4H5iXIPNSiJixogQo',
    appId: '1:386381768273:android:4b896caa1a8c55e0fd7a70',
    messagingSenderId: '386381768273',
    projectId: 'transmirror-8eedf',
    storageBucket: 'transmirror-8eedf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBriLopgZCU51fi17iGqLIoUiV62yqTr7o',
    appId: '1:386381768273:ios:a6321c1ac4b6a668fd7a70',
    messagingSenderId: '386381768273',
    projectId: 'transmirror-8eedf',
    storageBucket: 'transmirror-8eedf.firebasestorage.app',
    iosBundleId: 'com.transmirror.main',
  );
}
